title: La Maison en Pétales 🌼
logo: /assets/img/logo.png
description: Documentation pour auto-construire une Maison en Pétales
show_downloads: true
google_analytics: UA-67365635-1
theme: jekyll-theme-minimal
sponsor: https://fr.liberapay.com/Morses/
